# Generated by Django 3.0.7 on 2021-01-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuncTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checkpointimage',
            table='CheckpointImage',
        ),
    ]
