# Generated by Django 3.0.7 on 2021-01-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UIAutoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioId', models.IntegerField()),
                ('author', models.CharField(max_length=20, verbose_name='automation code author')),
                ('desc', models.CharField(max_length=120, verbose_name='automation code description')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('lastUdpateDate', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'UIAutoCode',
                'ordering': ['scenarioId'],
            },
        ),
        migrations.CreateModel(
            name='UIAutoScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioId', models.IntegerField()),
                ('desc', models.CharField(max_length=120, verbose_name='Scenarios description')),
                ('steps', models.TextField(verbose_name='Scenario steps')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('lastUdpateDate', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'UIAutoScenario',
                'ordering': ['scenarioId'],
            },
        ),
    ]
