# Generated by Django 3.0.7 on 2021-01-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UiAuto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uiautocode',
            options={'ordering': ['sautoId']},
        ),
        migrations.RemoveField(
            model_name='uiautocode',
            name='scenarioId',
        ),
        migrations.AddField(
            model_name='uiautocode',
            name='sautoId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UiAuto.UIAutoScenario', to_field='scenarioId'),
        ),
        migrations.AlterField(
            model_name='uiautoscenario',
            name='scenarioId',
            field=models.IntegerField(unique=True),
        ),
    ]
