# Generated by Django 3.0.7 on 2021-01-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UiAuto', '0002_auto_20210108_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiautocode',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uiautocode',
            name='lastUdpateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uiautoscenario',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uiautoscenario',
            name='lastUdpateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
