# Generated by Django 3.0.7 on 2021-01-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UiAuto', '0003_auto_20210108_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiautoscenario',
            name='isAutomated',
            field=models.BooleanField(default=False),
        ),
    ]
