# Generated by Django 3.0.7 on 2021-01-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAutoScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenarioId', models.IntegerField(unique=True)),
                ('desc', models.CharField(max_length=120, verbose_name='Scenarios description')),
                ('steps', models.TextField(verbose_name='Scenario steps')),
                ('isAutomated', models.BooleanField(default=False)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastUdpateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ApiAutoScenario',
                'ordering': ['scenarioId'],
            },
        ),
        migrations.CreateModel(
            name='ApiAutoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='automation code author')),
                ('desc', models.CharField(max_length=120, verbose_name='automation code description')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastUdpateDate', models.DateTimeField(auto_now=True)),
                ('sautoId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApiAuto.ApiAutoScenario', to_field='scenarioId')),
            ],
            options={
                'db_table': 'ApiAutoCode',
                'ordering': ['sautoId'],
            },
        ),
    ]
